"""add_dedup_fields_and_sha256_index

Revision ID: 1536321cf50e
Revises: b9bb54b68d7a
Create Date: 2026-03-08 13:58:54.043846

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1536321cf50e"
down_revision: Union[str, None] = "b9bb54b68d7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("artifacts", sa.Column("is_duplicate", sa.Boolean(), nullable=False))
    op.add_column("artifacts", sa.Column("duplicate_of", sa.Uuid(), nullable=True))
    op.create_foreign_key(None, "artifacts", "artifacts", ["duplicate_of"], ["id"])
    op.create_index("ix_artifacts_sha256", "artifacts", ["sha256"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_artifacts_sha256", "artifacts")
    op.drop_constraint(None, "artifacts", type_="foreignkey")
    op.drop_column("artifacts", "duplicate_of")
    op.drop_column("artifacts", "is_duplicate")
    # ### end Alembic commands ###
